DefaultClusterUrl : http://localhost:9200
Appearance:
    Theme: BaseLight
    Accent: Green

Endpoints :
    Indices :
        - _open
        - _close
        - _aliases
        - _warmers
        - _mappings
        - _settings
        - _mapping
        - _aliases
        - _analyze
        - _status
        - _stats
        - _segments
        - _recovery
        - _cache/clear
        - _refresh
        - _flush
        - _upgrade