IsOfflineMode : true
ReadPath : ..\\..\\data
SavePath : ..\\..\\data
ElasticSearchNodesEndpoints:
                             - http://localhost:9200
                             - http://localhost:9913