// Implementation file for parser generated by fsyacc
module IntellisenseParser
#nowarn "64";; // turn off warnings that type variables used in production annotations are instantiated to concrete type
open Microsoft.FSharp.Text.Lexing
open Microsoft.FSharp.Text.Parsing.ParseHelpers
# 1 "IntellisenseParser.fsy"

open ElasticOps.Parsing.Structures


# 11 "IntellisenseParser.fs"
// This type is the type of tokens accepted by the parser
type token = 
  | EOF
  | ANY_PATH
  | ANY_PROPERTY
  | UNFINISHED_VALUE of (string * ElasticOps.Parsing.Structures.JsonValueType)
  | COMPLETION_MACRO of (string)
  | COMMA
  | COLON
  | RIGHT_BRACK
  | LEFT_BRACK
  | RIGHT_BRACE
  | LEFT_BRACE
  | STRING of (string)
  | ID of (string)
// This type is used to give symbolic names to token indexes, useful for error messages
type tokenId = 
    | TOKEN_EOF
    | TOKEN_ANY_PATH
    | TOKEN_ANY_PROPERTY
    | TOKEN_UNFINISHED_VALUE
    | TOKEN_COMPLETION_MACRO
    | TOKEN_COMMA
    | TOKEN_COLON
    | TOKEN_RIGHT_BRACK
    | TOKEN_LEFT_BRACK
    | TOKEN_RIGHT_BRACE
    | TOKEN_LEFT_BRACE
    | TOKEN_STRING
    | TOKEN_ID
    | TOKEN_end_of_input
    | TOKEN_error
// This type is used to give symbolic names to token indexes, useful for error messages
type nonTerminalId = 
    | NONTERM__startstart
    | NONTERM_start
    | NONTERM_prog
    | NONTERM_value
    | NONTERM_object_fields
    | NONTERM_rev_object_fields
    | NONTERM_rev_values

// This function maps tokens to integers indexes
let tagOfToken (t:token) = 
  match t with
  | EOF  -> 0 
  | ANY_PATH  -> 1 
  | ANY_PROPERTY  -> 2 
  | UNFINISHED_VALUE _ -> 3 
  | COMPLETION_MACRO _ -> 4 
  | COMMA  -> 5 
  | COLON  -> 6 
  | RIGHT_BRACK  -> 7 
  | LEFT_BRACK  -> 8 
  | RIGHT_BRACE  -> 9 
  | LEFT_BRACE  -> 10 
  | STRING _ -> 11 
  | ID _ -> 12 

// This function maps integers indexes to symbolic token ids
let tokenTagToTokenId (tokenIdx:int) = 
  match tokenIdx with
  | 0 -> TOKEN_EOF 
  | 1 -> TOKEN_ANY_PATH 
  | 2 -> TOKEN_ANY_PROPERTY 
  | 3 -> TOKEN_UNFINISHED_VALUE 
  | 4 -> TOKEN_COMPLETION_MACRO 
  | 5 -> TOKEN_COMMA 
  | 6 -> TOKEN_COLON 
  | 7 -> TOKEN_RIGHT_BRACK 
  | 8 -> TOKEN_LEFT_BRACK 
  | 9 -> TOKEN_RIGHT_BRACE 
  | 10 -> TOKEN_LEFT_BRACE 
  | 11 -> TOKEN_STRING 
  | 12 -> TOKEN_ID 
  | 15 -> TOKEN_end_of_input
  | 13 -> TOKEN_error
  | _ -> failwith "tokenTagToTokenId: bad token"

/// This function maps production indexes returned in syntax errors to strings representing the non terminal that would be produced by that production
let prodIdxToNonTerminal (prodIdx:int) = 
  match prodIdx with
    | 0 -> NONTERM__startstart 
    | 1 -> NONTERM_start 
    | 2 -> NONTERM_prog 
    | 3 -> NONTERM_prog 
    | 4 -> NONTERM_value 
    | 5 -> NONTERM_value 
    | 6 -> NONTERM_object_fields 
    | 7 -> NONTERM_rev_object_fields 
    | 8 -> NONTERM_rev_object_fields 
    | 9 -> NONTERM_rev_object_fields 
    | 10 -> NONTERM_rev_object_fields 
    | 11 -> NONTERM_rev_object_fields 
    | 12 -> NONTERM_rev_object_fields 
    | 13 -> NONTERM_rev_object_fields 
    | 14 -> NONTERM_rev_object_fields 
    | 15 -> NONTERM_rev_object_fields 
    | 16 -> NONTERM_rev_object_fields 
    | 17 -> NONTERM_rev_values 
    | 18 -> NONTERM_rev_values 
    | _ -> failwith "prodIdxToNonTerminal: bad production index"

let _fsyacc_endOfInputTag = 15 
let _fsyacc_tagOfErrorTerminal = 13

// This function gets the name of a token as a string
let token_to_string (t:token) = 
  match t with 
  | EOF  -> "EOF" 
  | ANY_PATH  -> "ANY_PATH" 
  | ANY_PROPERTY  -> "ANY_PROPERTY" 
  | UNFINISHED_VALUE _ -> "UNFINISHED_VALUE" 
  | COMPLETION_MACRO _ -> "COMPLETION_MACRO" 
  | COMMA  -> "COMMA" 
  | COLON  -> "COLON" 
  | RIGHT_BRACK  -> "RIGHT_BRACK" 
  | LEFT_BRACK  -> "LEFT_BRACK" 
  | RIGHT_BRACE  -> "RIGHT_BRACE" 
  | LEFT_BRACE  -> "LEFT_BRACE" 
  | STRING _ -> "STRING" 
  | ID _ -> "ID" 

// This function gets the data carried by a token as an object
let _fsyacc_dataOfToken (t:token) = 
  match t with 
  | EOF  -> (null : System.Object) 
  | ANY_PATH  -> (null : System.Object) 
  | ANY_PROPERTY  -> (null : System.Object) 
  | UNFINISHED_VALUE _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
  | COMPLETION_MACRO _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
  | COMMA  -> (null : System.Object) 
  | COLON  -> (null : System.Object) 
  | RIGHT_BRACK  -> (null : System.Object) 
  | LEFT_BRACK  -> (null : System.Object) 
  | RIGHT_BRACE  -> (null : System.Object) 
  | LEFT_BRACE  -> (null : System.Object) 
  | STRING _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
  | ID _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
let _fsyacc_gotos = [| 0us; 65535us; 1us; 65535us; 0us; 1us; 1us; 65535us; 0us; 2us; 9us; 65535us; 0us; 4us; 10us; 11us; 14us; 15us; 17us; 18us; 20us; 21us; 23us; 24us; 26us; 27us; 29us; 30us; 32us; 33us; 1us; 65535us; 5us; 6us; 1us; 65535us; 5us; 8us; 0us; 65535us; |]
let _fsyacc_sparseGotoTableRowOffsets = [|0us; 1us; 3us; 5us; 15us; 17us; 19us; |]
let _fsyacc_stateToProdIdxsTableElements = [| 1us; 0us; 1us; 0us; 1us; 1us; 1us; 2us; 1us; 3us; 2us; 4us; 5us; 2us; 4us; 5us; 1us; 4us; 6us; 6us; 9us; 11us; 13us; 15us; 16us; 2us; 8us; 10us; 1us; 8us; 1us; 8us; 5us; 9us; 11us; 13us; 15us; 16us; 2us; 9us; 11us; 1us; 9us; 1us; 9us; 1us; 10us; 1us; 10us; 1us; 10us; 1us; 11us; 1us; 11us; 1us; 11us; 1us; 12us; 1us; 12us; 1us; 12us; 1us; 13us; 1us; 13us; 1us; 13us; 1us; 14us; 1us; 14us; 1us; 14us; 1us; 15us; 1us; 15us; 1us; 15us; |]
let _fsyacc_stateToProdIdxsTableRowOffsets = [|0us; 2us; 4us; 6us; 8us; 10us; 13us; 16us; 18us; 25us; 28us; 30us; 32us; 38us; 41us; 43us; 45us; 47us; 49us; 51us; 53us; 55us; 57us; 59us; 61us; 63us; 65us; 67us; 69us; 71us; 73us; 75us; 77us; 79us; |]
let _fsyacc_action_rows = 34
let _fsyacc_actionTableElements = [|2us; 32768us; 0us; 3us; 10us; 5us; 0us; 49152us; 0us; 16385us; 0us; 16386us; 0us; 16387us; 3us; 16391us; 1us; 28us; 2us; 22us; 11us; 9us; 1us; 16389us; 9us; 7us; 0us; 16388us; 1us; 16390us; 5us; 12us; 2us; 32768us; 4us; 16us; 6us; 10us; 1us; 32768us; 10us; 5us; 0us; 16392us; 3us; 16400us; 1us; 31us; 2us; 25us; 11us; 13us; 2us; 32768us; 4us; 19us; 6us; 14us; 1us; 32768us; 10us; 5us; 0us; 16393us; 1us; 32768us; 6us; 17us; 1us; 32768us; 10us; 5us; 0us; 16394us; 1us; 32768us; 6us; 20us; 1us; 32768us; 10us; 5us; 0us; 16395us; 1us; 32768us; 6us; 23us; 1us; 32768us; 10us; 5us; 0us; 16396us; 1us; 32768us; 6us; 26us; 1us; 32768us; 10us; 5us; 0us; 16397us; 1us; 32768us; 6us; 29us; 1us; 32768us; 10us; 5us; 0us; 16398us; 1us; 32768us; 6us; 32us; 1us; 32768us; 10us; 5us; 0us; 16399us; |]
let _fsyacc_actionTableRowOffsets = [|0us; 3us; 4us; 5us; 6us; 7us; 11us; 13us; 14us; 16us; 19us; 21us; 22us; 26us; 29us; 31us; 32us; 34us; 36us; 37us; 39us; 41us; 42us; 44us; 46us; 47us; 49us; 51us; 52us; 54us; 56us; 57us; 59us; 61us; |]
let _fsyacc_reductionSymbolCounts = [|1us; 1us; 1us; 1us; 3us; 2us; 1us; 0us; 3us; 5us; 4us; 6us; 3us; 5us; 3us; 5us; 2us; 1us; 3us; |]
let _fsyacc_productionToNonTerminalTable = [|0us; 1us; 2us; 2us; 3us; 3us; 4us; 5us; 5us; 5us; 5us; 5us; 5us; 5us; 5us; 5us; 5us; 6us; 6us; |]
let _fsyacc_immediateActions = [|65535us; 49152us; 16385us; 16386us; 16387us; 65535us; 65535us; 16388us; 65535us; 65535us; 65535us; 16392us; 65535us; 65535us; 65535us; 16393us; 65535us; 65535us; 16394us; 65535us; 65535us; 16395us; 65535us; 65535us; 16396us; 65535us; 65535us; 16397us; 65535us; 65535us; 16398us; 65535us; 65535us; 16399us; |]
let _fsyacc_reductions ()  =    [| 
# 162 "IntellisenseParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : ElasticOps.Parsing.Structures.IntellisenseValue option)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
                      raise (Microsoft.FSharp.Text.Parsing.Accept(Microsoft.FSharp.Core.Operators.box _1))
                   )
                 : '_startstart));
# 171 "IntellisenseParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'prog)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 26 "IntellisenseParser.fsy"
                                    _1 
                   )
# 26 "IntellisenseParser.fsy"
                 : ElasticOps.Parsing.Structures.IntellisenseValue option));
# 182 "IntellisenseParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 29 "IntellisenseParser.fsy"
                                 None 
                   )
# 29 "IntellisenseParser.fsy"
                 : 'prog));
# 192 "IntellisenseParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'value)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 30 "IntellisenseParser.fsy"
                                 Some _1 
                   )
# 30 "IntellisenseParser.fsy"
                 : 'prog));
# 203 "IntellisenseParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : 'object_fields)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 33 "IntellisenseParser.fsy"
                                                                Assoc _2 
                   )
# 33 "IntellisenseParser.fsy"
                 : 'value));
# 214 "IntellisenseParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : 'object_fields)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 34 "IntellisenseParser.fsy"
                                                                Assoc _2 
                   )
# 34 "IntellisenseParser.fsy"
                 : 'value));
# 225 "IntellisenseParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'rev_object_fields)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 36 "IntellisenseParser.fsy"
                                                        List.rev _1 
                   )
# 36 "IntellisenseParser.fsy"
                 : 'object_fields));
# 236 "IntellisenseParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 39 "IntellisenseParser.fsy"
                                                                                              [] 
                   )
# 39 "IntellisenseParser.fsy"
                 : 'rev_object_fields));
# 246 "IntellisenseParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'value)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 40 "IntellisenseParser.fsy"
                                                                                              [IntellisenseProperty.Property(_1,"|empty_object|",_3)] 
                   )
# 40 "IntellisenseParser.fsy"
                 : 'rev_object_fields));
# 258 "IntellisenseParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'rev_object_fields)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            let _5 = (let data = parseState.GetInput(5) in (Microsoft.FSharp.Core.Operators.unbox data : 'value)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 41 "IntellisenseParser.fsy"
                                                                                              IntellisenseProperty.Property(_3,"|empty_object|",_5) :: _1 
                   )
# 41 "IntellisenseParser.fsy"
                 : 'rev_object_fields));
# 271 "IntellisenseParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            let _4 = (let data = parseState.GetInput(4) in (Microsoft.FSharp.Core.Operators.unbox data : 'value)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 42 "IntellisenseParser.fsy"
                                                                                              [IntellisenseProperty.Property(_1,_2,_4)] 
                   )
# 42 "IntellisenseParser.fsy"
                 : 'rev_object_fields));
# 284 "IntellisenseParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'rev_object_fields)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            let _4 = (let data = parseState.GetInput(4) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            let _6 = (let data = parseState.GetInput(6) in (Microsoft.FSharp.Core.Operators.unbox data : 'value)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 43 "IntellisenseParser.fsy"
                                                                                              IntellisenseProperty.Property(_3,_4,_6) :: _1 
                   )
# 43 "IntellisenseParser.fsy"
                 : 'rev_object_fields));
# 298 "IntellisenseParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'value)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 44 "IntellisenseParser.fsy"
                                                                                              [IntellisenseProperty.AnyProperty(_3)] 
                   )
# 44 "IntellisenseParser.fsy"
                 : 'rev_object_fields));
# 309 "IntellisenseParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'rev_object_fields)) in
            let _5 = (let data = parseState.GetInput(5) in (Microsoft.FSharp.Core.Operators.unbox data : 'value)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 45 "IntellisenseParser.fsy"
                                                                                              IntellisenseProperty.AnyProperty(_5) :: _1 
                   )
# 45 "IntellisenseParser.fsy"
                 : 'rev_object_fields));
# 321 "IntellisenseParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'value)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 46 "IntellisenseParser.fsy"
                                                                                              [IntellisenseProperty.AnyPath(_3)] 
                   )
# 46 "IntellisenseParser.fsy"
                 : 'rev_object_fields));
# 332 "IntellisenseParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'rev_object_fields)) in
            let _5 = (let data = parseState.GetInput(5) in (Microsoft.FSharp.Core.Operators.unbox data : 'value)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 47 "IntellisenseParser.fsy"
                                                                                              IntellisenseProperty.AnyPath(_5) :: _1 
                   )
# 47 "IntellisenseParser.fsy"
                 : 'rev_object_fields));
# 344 "IntellisenseParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'rev_object_fields)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 48 "IntellisenseParser.fsy"
                                                                                              _1 
                   )
# 48 "IntellisenseParser.fsy"
                 : 'rev_object_fields));
# 355 "IntellisenseParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'value)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 51 "IntellisenseParser.fsy"
                                                  [_1] 
                   )
# 51 "IntellisenseParser.fsy"
                 : 'rev_values));
# 366 "IntellisenseParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'rev_values)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'value)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 52 "IntellisenseParser.fsy"
                                                  _3 :: _1 
                   )
# 52 "IntellisenseParser.fsy"
                 : 'rev_values));
|]
# 379 "IntellisenseParser.fs"
let tables () : Microsoft.FSharp.Text.Parsing.Tables<_> = 
  { reductions= _fsyacc_reductions ();
    endOfInputTag = _fsyacc_endOfInputTag;
    tagOfToken = tagOfToken;
    dataOfToken = _fsyacc_dataOfToken; 
    actionTableElements = _fsyacc_actionTableElements;
    actionTableRowOffsets = _fsyacc_actionTableRowOffsets;
    stateToProdIdxsTableElements = _fsyacc_stateToProdIdxsTableElements;
    stateToProdIdxsTableRowOffsets = _fsyacc_stateToProdIdxsTableRowOffsets;
    reductionSymbolCounts = _fsyacc_reductionSymbolCounts;
    immediateActions = _fsyacc_immediateActions;
    gotos = _fsyacc_gotos;
    sparseGotoTableRowOffsets = _fsyacc_sparseGotoTableRowOffsets;
    tagOfErrorTerminal = _fsyacc_tagOfErrorTerminal;
    parseError = (fun (ctxt:Microsoft.FSharp.Text.Parsing.ParseErrorContext<_>) -> 
                              match parse_error_rich with 
                              | Some f -> f ctxt
                              | None -> parse_error ctxt.Message);
    numTerminals = 16;
    productionToNonTerminalTable = _fsyacc_productionToNonTerminalTable  }
let engine lexer lexbuf startState = (tables ()).Interpret(lexer, lexbuf, startState)
let start lexer lexbuf : ElasticOps.Parsing.Structures.IntellisenseValue option =
    Microsoft.FSharp.Core.Operators.unbox ((tables ()).Interpret(lexer, lexbuf, 0))
